version: '3.8'

services:
  angular-app:
    image: angular-demo-app:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-demo-app
    ports:
      - "8088:80"
    restart: unless-stopped
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
